config/routes.rb
BounceTheRedBallEditor::Application.routes.draw do
  resources :mainconfigs

  resources :elements, :except => :destroy do
	collection do
		get 'details'
	end
	member do
	    post 'delete'
	end
  end

  resources :types

  resources :niveaus do
    member do
		get 'screen'
		get 'serialize'
		post 'fastedit'
	end
  
  collection do
    get 'serialize_all'
  end
  
  end









  root :to => "niveaus#index"


end

app/models/mainconfig.rb
class Mainconfig < ActiveRecord::Base
end

app/controllers/mainconfigs_controller.rb
class MainconfigsController < ApplicationController
  # GET /mainconfigs
  # GET /mainconfigs.xml
  def index
    @mainconfigs = Mainconfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mainconfigs }
    end
  end

  # GET /mainconfigs/1
  # GET /mainconfigs/1.xml
  def show
    @mainconfig = Mainconfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mainconfig }
    end
  end

  # GET /mainconfigs/new
  # GET /mainconfigs/new.xml
  def new
    @mainconfig = Mainconfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mainconfig }
    end
  end

  # GET /mainconfigs/1/edit
  def edit
    @mainconfig = Mainconfig.find(params[:id])
  end

  # POST /mainconfigs
  # POST /mainconfigs.xml
  def create
    @mainconfig = Mainconfig.new(params[:mainconfig])

    respond_to do |format|
      if @mainconfig.save
        format.html { redirect_to(@mainconfig, :notice => 'Mainconfig was successfully created.') }
        format.xml  { render :xml => @mainconfig, :status => :created, :location => @mainconfig }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mainconfig.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mainconfigs/1
  # PUT /mainconfigs/1.xml
  def update
    @mainconfig = Mainconfig.find(params[:id])

    respond_to do |format|
      if @mainconfig.update_attributes(params[:mainconfig])
        format.html { redirect_to(niveaus_path) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mainconfig.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mainconfigs/1
  # DELETE /mainconfigs/1.xml
  def destroy
    @mainconfig = Mainconfig.find(params[:id])
    @mainconfig.destroy

    respond_to do |format|
      format.html { redirect_to(mainconfigs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/mainconfigs_helper.rb
module MainconfigsHelper
end

app/views/mainconfigs/_form.html.erb
<%= form_for(@mainconfig) do |f| %>
  <% if @mainconfig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mainconfig.errors.count, "error") %> prohibited this mainconfig from being saved:</h2>

      <ul>
      <% @mainconfig.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :root %><br />
    <%= f.text_field :root %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mainconfigs/edit.html.erb
<h1>Editing mainconfig</h1>

<%= render 'form' %>

<%= link_to 'Back', niveaus_path %>

app/views/mainconfigs/index.html.erb
<h1>Listing mainconfigs</h1>

<table>
  <tr>
    <th>Root</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mainconfigs.each do |mainconfig| %>
  <tr>
    <td><%= mainconfig.root %></td>
    <td><%= link_to 'Show', mainconfig %></td>
    <td><%= link_to 'Edit', edit_mainconfig_path(mainconfig) %></td>
    <td><%= link_to 'Destroy', mainconfig, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mainconfig', new_mainconfig_path %>

app/views/mainconfigs/new.html.erb
<h1>New mainconfig</h1>

<%= render 'form' %>

<%= link_to 'Back', mainconfigs_path %>

app/views/mainconfigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Root:</b>
  <%= @mainconfig.root %>
</p>


<%= link_to 'Edit', edit_mainconfig_path(@mainconfig) %> |
<%= link_to 'Back', mainconfigs_path %>