config/routes.rb
BounceTheRedBallEditor::Application.routes.draw do
  resources :mainconfigs

  resources :elements, :except => :destroy do
	collection do
		get 'details'
	end
	member do
	    post 'delete'
	end
  end

  resources :types

  resources :niveaus do
    member do
		get 'screen'
		get 'serialize'
		post 'fastedit'
	end
  
  collection do
    get 'serialize_all'
  end
  
  end









  root :to => "niveaus#index"


end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :type
  belongs_to :niveau
  has_many :options, :dependent => :delete_all
  accepts_nested_attributes_for :options, :allow_destroy => true
  
  validate :not_already_something, :on => :create
  def not_already_something
	errors.add(:x, "Coordinate already occupied by another element") unless Element.where("niveau_id=? and x=? and y=?", self.niveau_id, self.x, self.y).count < 1
  end
  
  after_create :init_options
  def init_options
	# en fonction du type, initialiser les options de type key/value
	
	# xG
	if self.type_id==6
		self.options.create({:name=>'coef', :value=>'2'})
	end
	
	# spike
	if self.type_id==5
		self.options.create({:name=>'orientation', :value=>'top'})
	end
	
	# sprite conditionnel
	if self.type_id==10
		self.options.create({:name=>'fichier', :value=>'top'})
	end
	
	# sprite pente
	if self.type_id==11
		self.options.create({:name=>'orientation', :value=>'NW'})
	end
	
	# platform
	if self.type_id==13
		self.options.create({:name=>'orientation', :value=>'normal'})
    self.options.create({:name=>'deltax', :value=>'16'})
	end
  
  end
  
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController

  layout nil

  #GET /elements/details
  def details
	x=params[:x]
	y=params[:y]
	niveau_id=params[:niveauId]
	
	res = Element.where("niveau_id=? AND x=? AND y=?", niveau_id, x, y)
	if res.size == 0
		redirect_to :controller=>'elements', :action=>'new', :y=>y, :x=>x, :niveauId=>niveau_id
	else 
		if res.size == 1
			redirect_to :controller=>'elements', :action=>'edit', :id=>res[0].id
		else 
			render :text=>"error"
		end
	end
	
  end
  

  # GET /elements
  # GET /elements.xml
  def index
    @elements = Element.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @elements }
    end
  end


  # GET /elements/new
  # GET /elements/new.xml
  def new
    @element = Element.new

	x=params[:x]
	y=params[:y]
	niveau_id=params[:niveauId]
	
	@element.x=x
	@element.y=y
	@element.niveau_id=niveau_id
	
	@types = Type.find(:all)
	@selected_type = @types.first
	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @element }
    end
  end

  # GET /elements/1/edit
  def edit
    @element = Element.find(params[:id])
	@types = Type.find(:all)
	@selected_type = @types.first
  end

  # POST /elements
  # POST /elements.xml
  def create
    @element = Element.new(params[:element])

	
    if @element.save
      render :text => 'Element was successfully created.'
    else
      render :text => 'Error creating this element.'
    end
    
  end

  # PUT /elements/1
  # PUT /elements/1.xml
  def update
    @element = Element.find(params[:id])

    if @element.update_attributes(params[:element])
      render :text => 'Element was successfully update.'
    else
      render :text => 'Error updating this element.'
    end
    
  end

  # POST /elements/delete/1
  def delete
    @element = Element.find(params[:id])
    @element.destroy

    render :text => 'Element destroyed'
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_form.html.erb
<%= form_for(@element) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :niveau_id %>
  <%= f.hidden_field :y %>
  <%= f.hidden_field :x %>
  
  <% if controller.action_name=="new" %>
	  <div class="field">
		<%= label_tag :type %><br />
		<%= select("element", "type_id", @types.map {|u| [u.label, u.id]}) %>
	  </div>
  <% end %>
  
  <% if controller.action_name=="edit" %>
  
	<%= f.fields_for :options do |o| %>
		<div class="field">
			<%= label_tag o.object.name %>
			<%= o.text_field :value %>
		</div>
	<% end %>
  
  <% end %>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Type <%= @element.type.label %> [<%= @element.x %>, <%= @element.y %>]</h1>

<%= render 'form' %>


<%= form_tag delete_element_path(@element) do %>
	<div class="actions">
		<%= submit_tag "Delete" %>
	</div>
<% end %>

app/views/elements/index.html.erb
<h1>Listing elements</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Niveau</th>
    <th>X</th>
    <th>Y</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @elements.each do |element| %>
  <tr>
    <td><%= element.type %></td>
    <td><%= element.niveau %></td>
    <td><%= element.x %></td>
    <td><%= element.y %></td>
    <td><%= link_to 'Show', element %></td>
    <td><%= link_to 'Edit', edit_element_path(element) %></td>
    <td><%= link_to 'Destroy', element, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Element', new_element_path %>

app/views/elements/new.html.erb
<h1>Case vide [<%= @element.x %>, <%= @element.y %>]</h1>

<%= render 'form' %>