config/routes.rb
BounceTheRedBallEditor::Application.routes.draw do
  resources :mainconfigs

  resources :elements, :except => :destroy do
	collection do
		get 'details'
	end
	member do
	    post 'delete'
	end
  end

  resources :types

  resources :niveaus do
    member do
		get 'screen'
		get 'serialize'
		post 'fastedit'
	end
  
  collection do
    get 'serialize_all'
  end
  
  end









  root :to => "niveaus#index"


end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.xml
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @types }
    end
  end

  # GET /types/1
  # GET /types/1.xml
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @type }
    end
  end

  # GET /types/new
  # GET /types/new.xml
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.xml
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to(@type, :notice => 'Type was successfully created.') }
        format.xml  { render :xml => @type, :status => :created, :location => @type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.xml
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to(types_path, :notice => 'Type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.xml
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to(types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :cssClass %><br />
    <%= f.text_field :cssClass %>
  </div>
  <div class="field">
    <%= f.label :xmlTag %><br />
    <%= f.text_field :xmlTag %>
  </div>
  <div class="field">
    <%= f.label :perfVoisin %><br />
    <%= f.check_box :perfVoisin %>
  </div>
  <div class="field">
    <%= f.label :isSegment %><br />
    <%= f.check_box :isSegment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Types d'elements</h1>


<%= link_to 'Nouveau type', new_type_path %>
 | 
<%= link_to 'Retour a la liste des niveaux', niveaus_path %>
<br/>
<br/>


<table  border=1 cellpadding=0 cellspacing=0>
  <tr>
    <th>Ex.</th>
	<th>Id</th>
    <th>Type</th>
    <th>Classe css</th>
    <th>Balise xml</th>
    <th>Calcul des attributs <br/> pour les perfs</th>
    <th>Transformer en <br/>segment egalement ?</th>
    <th></th>
    <th></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td>
    
    <div class="<%= type.cssClass %>" 
style="width:16px;height:16px;"></div>

    </td>
    <td><%= type.id %></td>
    <td><%= type.label %></td>
    <td><%= type.cssClass %></td>
    <td><%= type.xmlTag %></td>
    <td><%= (type.perfVoisin)?'YES':'' %></td>
    <td><%= (type.isSegment)?'YES':'' %></td>
    <td><%= link_to 'Destroy', type, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'Edit', edit_type_path(type) %></td>
  </tr>
<% end %>
</table>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @type.label %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>