config/routes.rb
BounceTheRedBallEditor::Application.routes.draw do
  resources :mainconfigs

  resources :elements, :except => :destroy do
	collection do
		get 'details'
	end
	member do
	    post 'delete'
	end
  end

  resources :types

  resources :niveaus do
    member do
		get 'screen'
		get 'serialize'
		post 'fastedit'
	end
  
  collection do
    get 'serialize_all'
  end
  
  end









  root :to => "niveaus#index"


end

app/models/niveau.rb
class Niveau < ActiveRecord::Base
	has_many :elements
  
  before_create :default
  def default
	 self.isReallyDeleted=false unless !self.isDeleted.nil?
	 self.isTest=false unless !self.isTest.nil?
  end
  
  def bgImageCss
    if self.bgImage.blank?
      return ""
    else
      return "background-image:url('../../images/bg/#{self.bgImage}')"
    end
  end

  def serialize
    fileName = "lvl-#{self.tier}-#{self.numero}.xml"
    filePath = Mainconfig.find(1).root
    
    File.open("#{filePath}/#{fileName}" , 'w') do |f| 
		f.puts("<level number='#{self.numero}' tier='#{self.tier}' title='#{self.titre}' type='#{self.thetype}'>")
		
		self.elements.each do |element|
			currentLine = "\t<#{element.type.xmlTag} x='#{(element.x-0.5) * 16}' y='#{(element.y-0.5) * 16}'"

			element.options.each do |option|
				currentLine << " #{option.name}='#{option.value}'"
			end
			
      if element.type.perfVoisin 
        
        hasOneAbove=false
        hasOneBelow=false
        hasOneOnTheRight=false
        hasOneOnTheLeft=false
        
        if element.x==1
          hasOneOnTheLeft=true
        end
        if element.x==20
          hasOneOnTheRight=true
        end
        if element.y==1
          hasOneBelow=true
        end
        if element.y==30
          hasOneAbove=true
        end
        
        if !hasOneOnTheLeft
          res=Element.where("niveau_id=? and x=? and y=?", self.id,element.x-1, element.y)
          if res.count == 1
            if res[0].type.perfVoisin || res[0].type.id==5|| (res[0].type.id=11 && (res[0].options.first=="NW" || res[0].options.first=="SW"))
              hasOneOnTheLeft=true
            end
          end
        end
        
        if !hasOneOnTheRight
          res=Element.where("niveau_id=? and x=? and y=?", self.id,element.x+1, element.y)
          if res.count == 1
            if res[0].type.perfVoisin || res[0].type.id==5|| (res[0].type.id=11 && (res[0].options.first=="NE" || res[0].options.first=="SE"))
              hasOneOnTheRight=true
            end
          end
        end
        
        if !hasOneBelow
          res=Element.where("niveau_id=? and x=? and y=?", self.id,element.x, element.y-1)
          if res.count == 1
            if res[0].type.perfVoisin || res[0].type.id==5|| (res[0].type.id=11 && (res[0].options.first=="SE" || res[0].options.first=="SW"))
              hasOneBelow=true
            end
          end
        end
        
        if !hasOneAbove
          res=Element.where("niveau_id=? and x=? and y=?", self.id,element.x, element.y+1)
          if res.count == 1
            if res[0].type.perfVoisin || res[0].type.id==5|| (res[0].type.id=11 && (res[0].options.first=="NE" || res[0].options.first=="NW"))
              hasOneAbove=true
            end
          end
        end
        
        currentLine << " hasOneAbove='#{(hasOneAbove)?"1":"0"}' hasOneBelow='#{(hasOneBelow)?"1":"0"}' hasOneOnTheRight='#{(hasOneOnTheRight)?"1":"0"}' hasOneOnTheLeft='#{(hasOneOnTheLeft)?"1":"0"}' "
        
      end
      
			currentLine << "></#{element.type.xmlTag}>"
			
			f.puts(currentLine)
		end
		
		f.puts("</level>")
	end
  end
end

app/controllers/niveaus_controller.rb

class NiveausController < ApplicationController
  
  # POST /niveaus/fastedit/1/
  def fastedit
	@niveau=Niveau.find(params[:id])
	type_id=params[:fastedittype]
	coordinates=params[:coordinates]
	
	tab_coordinates=coordinates.split(";")
	tab_coordinates.each do |coordinate|
		x=coordinate[1,coordinate.index(",")-1].to_i
		y=coordinate[coordinate.index(",")+1,coordinate.rindex("]")-3].to_i
		
		if type_id=="delete"
		  Element.where("x=? and y=? and niveau_id=?", x, y, @niveau.id).delete_all
		else
		  new_element=Element.new({:x=>x, :y=>y, :type_id=>type_id, :niveau_id=>@niveau.id})
		  new_element.save
		end
	end
	
	render :text=>"Saved !!", :layout=>false
  end
  
  # POST /niveaus/serialize_all
  def serialize_all
    Niveau.all.each do |n|
      n.serialize
    end
    redirect_to niveaus_path
  end
  
  # GET /niveaus/serialize/1/
  def serialize
	  @niveau = Niveau.find(params[:id])
	  @niveau.serialize
	  redirect_to edit_niveau_path(@niveau)
  end
  
  # GET /niveaus/screen/1/
  def screen
	@niveau = Niveau.find(params[:id])
	render :layout=>false
  end
  
  # GET /niveaus
  # GET /niveaus.xml
  def index
    @niveaus = Niveau.order("isReallyDeleted, isTest,tier asc,numero")
    @mainconfig = Mainconfig.find(1)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @niveaus }
    end
  end

  # GET /niveaus/1
  # GET /niveaus/1.xml
  def show
    @niveau = Niveau.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @niveau }
    end
  end

  # GET /niveaus/new
  def new
    @niveau = Niveau.new
  end

  # GET /niveaus/1/edit
  def edit
    @niveau = Niveau.find(params[:id])
	@niveaus = Niveau.where("isReallyDeleted=? and isTest=?",false,false).order("tier asc,numero")
	@types = Type.find(:all)
  end

  # POST /niveaus
  def create
    @niveau = Niveau.new(params[:niveau])

    if @niveau.save
      redirect_to edit_niveau_path(@niveau)
    else
      render :action => "new"
    end
  end

  # PUT /niveaus/1
  # PUT /niveaus/1.xml
  def update
    @niveau = Niveau.find(params[:id])

	if @niveau.update_attributes(params[:niveau])
	  redirect_to edit_niveau_path(@niveau)
	else
	  render :action => "edit" 
	end
  end

  # DELETE /niveaus/1
  # DELETE /niveaus/1.xml
  def destroy
    @niveau = Niveau.find(params[:id])
    @niveau.destroy

    respond_to do |format|
      format.html { redirect_to(niveaus_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/niveaus_helper.rb
module NiveausHelper
end

app/views/niveaus/_active_lists.html.erb

<% previousTier=1
   @niveaus.each do |n| 
	
	if previousTier!=n.tier
	%>
		<br/>
	<%
	end
	%>
	
	<%= link_to "#{n.tier} #{n.numero}", edit_niveau_path(n) %>  | 
	
	<%
	previousTier=n.tier
   end %>

app/views/niveaus/_editor.html.erb
<input type="hidden" id="niveau_id" value="<%= @niveau.id %>"/>
<table><tr><td valign=top>

<div id="iphone">

	<div id="screen" style="<%= @niveau.bgImageCss %>">
	
		<%= render 'screen' %>
	
	</div>

	<div id="case"></div>
	
</div>

</td><td  valign=top>

<div id="editbox">
	<div id="coordonnees">
	</div>

	<div id="details"></div>
	<div id="fastedit">
		<b>fastedit!</b>
		<label for="fastedittype">Choose a type</label>
		
		<% form_tag fastedit_niveau_path(@niveau) do %>
			<select id="fastedittype" name="fastedittype">
				<option value="delete">Gomme magique :p</option>
				<option disabled>--------- types normaux: ----</option>
				<% @types.each do |type| %>
					<option data-cssClass="<%= type.cssClass %>" value="<%= type.id %>"><%= type.label %></option>
				<% end %>
			</select>
			<br/>
			<a href="#" id="beginfastedit">Begin fast edit with this type !</a>
						
			<%= hidden_field_tag "coordinates" %>
			
			<div id="fastedit-actions" style="display:none;">
				<%= submit_tag "Valider" %>
				<a href="#" id="annulerfastedit">Annuler</a>
			</div>
		<% end %>
		
		<div id="feedback"></div>
		
	</div>
</div>

</td></tr></table>

<script id="coordonnees-template" type="text/x-underscore-template">
  {{x}} - {{y}}
</script>

app/views/niveaus/_form.html.erb
<%= form_for(@niveau) do |f| %>
  <% if @niveau.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@niveau.errors.count, "error") %> prohibited this niveau from being saved:</h2>

      <ul>
      <% @niveau.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tier %><br />
    <%= f.text_field :tier %>
  </div>
  <div class="field">
    <%= f.label :numero %><br />
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :titre %><br />
    <%= f.text_field :titre %>
  </div>
  <div class="field">
    <%= f.label :bgImage %><br />
    <%= f.text_field :bgImage %>
  </div>  
  <div class="field">
    <%= f.label :thetype %><br />
    <%= f.select( :thetype, options_for_select([['Exit this level', 'exit'], ['Time trial', 'time'],['Free your friends', 'friends']], @niveau.thetype)) %>
    
  </div>  
  <div class="field">
    <%= f.label :isTest %><br />
    <%= f.check_box :isTest %>
  </div>
  <div class="field">
    <%= f.label :isReallyDeleted %><br />
    <%= f.check_box :isReallyDeleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/niveaus/_screen.html.erb
<% @niveau.elements.each do |element| %>

	<%
		cssClass=""
		cssClass=element.type.cssClass
		if [5,11,13].include?(element.type_id)
			
			cssClass = "#{element.type.cssClass} #{element.options.where('name=?','orientation')[0].value}"
		end
		
		left=(element.x-1)*16
		top=480-(element.y)*16
		
		if element.type_id==13
			orientation = element.options.where('name=?','orientation')[0].value
			if orientation=="inverse"
				top=top+4
			else
				top=top-4
			end
		end
	%>


	<div class="case <%= cssClass %>" 
		 style="left:<%= left %>px;top:<%= top %>px;width:16px;height:16px">
	</div>
	
	<%
		if element.type_id==13
			dx = element.options.where('name=?','deltax')[0].value
			
			if orientation=="inverse"
				top=top+8
			else 
				top=top+1
			end
			
			%>
			
			<div class="platform-helper" style="left:<%= left+16 %>px;top:<%= top+2 %>px;width:<%= dx %>px"></div>
			
			<%
		
		end
	%>
	 
<% end %>

app/views/niveaus/edit.html.erb
<section id="other_levels">
	<%= render 'active_lists' %>
</section>


<section id="level_data">
	<h1><%= @niveau.titre %></h1>
	<%= render 'form' %>
</section>

<section id="level_toolbar">
	<b><%= link_to 'Serializer', serialize_niveau_path(@niveau) %></b> |
	<%= link_to 'Retour a la liste', niveaus_path %>
</section>

<section id="level_editor">
	<%= render 'editor' %>
</section>

app/views/niveaus/index.html.erb
<h1>Niveaux</h1>

<%= link_to 'Nouveau niveau', new_niveau_path %>
 | 
<%= link_to 'Types d''elements dans un niveau', types_path %>
 |
<%= link_to 'Main config', edit_mainconfig_path(@mainconfig)  %>
 |
<%= link_to 'Serialize all', serialize_all_niveaus_path %>
<br/>
<br/>

<table border=1 cellpadding=0 cellspacing=0 style="border-color:#000;">
  <tr>
    <th>Deleted ?</th>
	<th>Test ?</th>
    <th>Couleur</th>
	<th>Tier</th>
    <th>Numero</th>
    <th>Titre</th>
    <th></th>
    <th></th>
	<th>Inventaire</th>
  </tr>

<% @niveaus.each do |niveau| %>

	<%
	bgColor="#ffffff"
	if (!niveau.isReallyDeleted and !niveau.isTest)
		if niveau.tier==1 
			bgColor="#0B5FA5"
		end
		if niveau.tier==2
			bgColor="#A66000"
		end
		if niveau.tier==3 
			bgColor="#389E28"
		end
		if niveau.tier==4 
			bgColor="#A2000C"
		end
	end
	%>

  <tr>
	<td><%= (niveau.isReallyDeleted)?'DELETED':'' %></td>
	<td><%= (niveau.isTest)?'TEST':'' %></td>
    <td style="background-color:<%= bgColor %>"></td>
	<td><%= niveau.tier %></td>
	<td><%= niveau.numero %></td>
    <td><%= niveau.titre %></td>
    <td><%= link_to 'Edit', edit_niveau_path(niveau) %></td>
    <td><%= link_to 'Destroy', niveau, :confirm => 'Are you sure?', :method => :delete %></td>
	<td>
	<%
	Type.all.each do |t|
		countType=niveau.elements.where("type_id=?",t.id).count
		if  countType > 0
			%>
			<div class="<%= t.cssClass %>" style="width:16px;height:16px;display:inline-block"></div>x<%= countType%> 
			<%
		end
	end
	%>
	</td>
  </tr>
<% end %>
</table>

app/views/niveaus/new.html.erb
<h1>New niveau</h1>

<%= render 'form' %>

<%= link_to 'Back', niveaus_path %>

app/views/niveaus/screen.html.erb
<%= render "screen" %>

app/views/niveaus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Numero:</b>
  <%= @niveau.numero %>
</p>

<p>
  <b>Titre:</b>
  <%= @niveau.titre %>
</p>


<%= link_to 'Edit', edit_niveau_path(@niveau) %> |
<%= link_to 'Back', niveaus_path %>